### ISSUE TITLE
pin nixpkgs to ensure nix-shell works

### ISSUE THREAD

**Issue by willbush** [gvolpe/shopping-cart-haskell#2]
Hey, I was checking out your blog post about setting up ghcide. Thought I would
clone your repo and give it a whirl. However, I am running into the following error:

```
λ ~/code/shopping-cart-haskell/ master nix-shell
error: Package ‘refined-0.4.4’ in /nix/store/3m9z2vfr0fnfdgrshyy70cidhyp5wbkz-nixos-20.09pre217537.d96bd3394b7/nixos/pkgs/development/haskell-modules/hackage-packages.nix:202905 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

I think the best solution is to pin nixpkgs to a working revision of the repository.

Here are some links that go into how one might do that:

- https://github.com/Gabriel439/haskell-nix
- https://www.fosskers.ca/blog/nix-en.html
- https://www.haskell.org/cabal/users-guide/nix-integration.html
- https://cah6.github.io/technology/nix-haskell-1/
- https://cah6.github.io/technology/nix-haskell-2/

I haven't been following the latest trends in how to setup Haskell projects with
nix so those might already be out of date. I've noticed some people use
https://input-output-hk.github.io/haskell.nix/, but that might be overkill and
the build times are insane unless you setup cachix and pin to a known revision
that the CI ran for and cached.

I tried this revision of the unstable branch where refined is not marked broken:

```json
{
  "url": "https://github.com/nixos/nixpkgs-channels.git",
  "rev": "7e5690c088a542d979afab26a5f0f60f37fe2a98",
  "date": "2020-02-28T20:42:15+01:00",
  "sha256": "1gd9giqngr64ms6gjbbhygm2c53kyrrfxs9yhc8dnsh9blhg8cg4",
  "fetchSubmodules": false,
  "deepClone": false,
  "leaveDotGit": false
}
```

Generated using:

```
nix-prefetch-git https://github.com/nixos/nixpkgs-channels.git refs/heads/nixos-unstable > ./nix/nixos-unstable.json --rev 7e5690c088a542d979afab26a5f0f60f37fe2a98
```

with a `release.nix` of:

```nix
let
  pinnedPkgs = import ./nix/pkgs-from-json.nix { json = ./nix/nixos-unstable.json; };
in
  pinnedPkgs.haskellPackages.callPackage ./default.nix { nixpkgs = pinnedPkgs; }
```

and `./nix/pkgs-from-json.nix`:

```nix
{ json }:
let
  bootstrapPkgs = import <nixpkgs> {};
  nixpkgs = builtins.fromJSON (builtins.readFile json);
  src = bootstrapPkgs.fetchFromGitHub {
    owner = "NixOS";
    repo  = "nixpkgs-channels";
    inherit (nixpkgs) rev sha256;
  };
in
  import src {}
```

Unfortunately, I get this error instead:

```
...
builder for '/nix/store/jhlxyb0jny3810zls9f9mpwmbzysji5w-cryptonite-0.26.drv' failed with exit code 1
cannot build derivation '/nix/store/k33zyqwj9hpv70kmqkawi209gmxzcvp4-ghc-8.6.5-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/k33zyqwj9hpv70kmqkawi209gmxzcvp4-ghc-8.6.5-with-packages.drv' failed
```

I stopped looking at that point. If it's working with your nixpkgs, consider pinning it to that version.

**Comment by gvolpe** [comment]
Hey @willbush ,

Thanks for reporting it. I'll try to pin Nixpkgs to my current (working) version :+1:

**Comment by soupi** [comment]
Hi, I'm still getting the same issue trying to run nix-shell:

```
➜  shopping-cart-haskell git:(master) nix-shell
error: Package ‘refined-0.4.4’ in /nix/store/in95j6pwbgzr5bxncqv3iaav5nx0yik2-source/pkgs/development/haskell-modules/hackage-packages.nix:203991 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

I'm on commit:

```
commit efafe9a2f56baa809cde78ae7118f9e11a647ee3 (HEAD -> master, origin/master, origin/HEAD)
Author: Gabriel Volpe <volpegabriel@gmail.com>
Date:   Fri Mar 27 16:58:21 2020 +0100

    removing unlift dependency
```

which as far as I know is the latest at the moment.

**Comment by gvolpe** [comment]
@soupi you need to have this option in your configuration:

```nix
{ nixpkgs.config.allowBroken = true; }
```

Unfortunately, the `refined` package is mistakenly marked as broken in `nixpkgs`. See https://github.com/gvolpe/shopping-cart-haskell/pull/3

**Comment by soupi** [comment]
@gvolpe Thanks for the explanation. I've run 
```
➜  ~ mkdir .config/nixpkgs
➜  ~ echo "{ allowBroken = true; }" > ~/.config/nixpkgs/config.nix
```
as suggested and was able to to go pass that issue. Perhaps this should be added to the readme?

I did however still fail with the following error:

```
error: getting attributes of path '/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh': No such file or directory
```

**Comment by gvolpe** [comment]
I didn't want to add it to the README because this is common with `nixpkgs` and should be fixed upstream. See https://github.com/NixOS/nixpkgs/issues/83445

> `error: getting attributes of path '/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh': No such file or directory`

Mmm that's interesting. Can you provide more details of your environment? Run `nix-shell -p nix-info --run nix-info` and paste the details below, please.

**Comment by soupi** [comment]
Thank you for the help. This doesn't look right so I don't know if this is going to be of use though:

```
➜  shopping-cart-haskell git:(master) nix-shell -p nix-info --run nix-info
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
build input /nix/store/mjjy30kxz775bhhi6j9phw81qh6dsbrf-move-docs.sh does not exist
```

**Comment by gvolpe** [comment]
Oh that could be related to LOCALEs which can happen if you're not in NixOS. I have this in my `.bashrc`, maybe it works for you.

```
export LC_ALL="en_US.UTF-8"
export LOCALE_ARCHIVE_2_11="$(nix-build --no-out-link "<nixpkgs>" -A glibcLocales)/lib/locale/locale-archive"
export LOCALE_ARCHIVE_2_27="$(nix-build --no-out-link "<nixpkgs>" -A glibcLocales)/lib/locale/locale-archive"
export LOCALE_ARCHIVE="/usr/bin/locale"
```

**Comment by soupi** [comment]
Thanks. I am on Ubuntu and this is pretty much a clean installation of nix. Unfortunately I tried making the changes you suggested but without change.

I think we are getting off topic for this ticket and while I'm still up for trying to get around this issue, please don't feel obligated to help if you don't have the time or energy right now :)

**Comment by gvolpe** [comment]
Oh no worries, I'd be happy to help you as I've been on the same boat. I'm also on Ubuntu (19.10).
